### ISSUE TITLE
Could not get unknown property 'latest_version' 

### ISSUE THREAD

**Issue by puretsang** [ksughosh/AnimatedTextView#1]
Error:(97, 0) Could not get unknown property 'latest_version' for object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
![59c1fe4d-f561-4ae6-ac0e-efbef3352539](https://user-images.githubusercontent.com/7402617/28700488-9c919d28-7382-11e7-8df1-6b31d8da3965.png)

**Comment by ksughosh** [comment]
Define the `latest_version` to the latest release available like `1.0` in your gradle or replace `$latest_version` with `1.0`
